FROM node:latest as build

ENV REACT_APP_API_URL='/api'

WORKDIR /app

COPY ./package.json /app/package.json
COPY ./package-lock.json /app/package-lock.json
COPY ./allieandisaacwedding_site /app/ssl

RUN npm install
COPY . .
RUN npm run build

FROM nginx
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html
COPY --from=build /app/ssl /usr/share/nginx/ssl
