services:
  wed-reg-client:
    build: ./wed-reg-client
    command: sh -c 'sleep 10s ; npm start'
    depends_on:
      - wed-reg-db
    ports:
    - 3000:3000
  wed-reg-api:
    build: ./wed-reg-api
    command: sh -c "sleep 10s ; npm start"
    depends_on:
      - wed-reg-db
    ports:
      - 8080:8080

  wed-reg-db:
    build: ./wed-reg-db
    command: mysqld --authentication_policy=mysql_native_password
    environment:
      MYSQL_DATABASE: "wedding"
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3307:3306"