services:
  client:
    build: 
      context: ./client
    restart: unless-stopped
    ports:
    - 80:80
    networks: 
      - frontend
      - backend

  api:
    build: 
      context: ./api
    restart: unless-stopped
    command: sh -c "sleep 10s ; npm start"
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - backend

  db:
    build: ./db
    restart: unless-stopped
    command: mysqld --authentication_policy=mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - type: volume
        source: db-data
        target: /data
        volume:
          nocopy: true
    networks:
      - backend

volumes:
  db-data:

networks:
  frontend:
  backend: