services:
  wed-reg-client:
    build: ./wed-reg-client
    restart: unless-stopped
    command: sh -c 'sleep 10s ; npm start'
    depends_on:
      - wed-reg-api
    ports:
    - 3000:3000

  wed-reg-api:
    build: ./wed-reg-api
    restart: unless-stopped
    command: sh -c "sleep 10s ; npm start"
    depends_on:
      - wed-reg-db
    env_file:
      - ./wed-reg-api/.env
    ports:
      - 8080:8080

  wed-reg-db:
    build: ./wed-reg-db
    restart: unless-stopped
    command: mysqld --authentication_policy=mysql_native_password
    env_file:
      - ./wed-reg-db/.env
    ports:
      - "3307:3306"
    volumes:
      - type: volume
        source: db-data
        target: /data
        volume:
          nocopy: true

volumes:
  db-data: