services:
  client:
    build: ./client
    restart: unless-stopped
    command: sh -c 'sleep 10s ; npm start'
    ports:
    - 3000:3000

  api:
    build: ./api
    restart: unless-stopped
    command: sh -c "sleep 10s ; npm start"
    depends_on:
      - db
    ports:
      - 8080:8080

  db:
    build: ./db
    restart: unless-stopped
    command: mysqld --authentication_policy=mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - type: volume
        source: db-data
        target: /data
        volume:
          nocopy: true

volumes:
  db-data: