services:
  wed-reg-api:
    build: ./wed-reg-api
    depends_on:
      - wed-reg-db
    ports:
      - 8080:8080

  wed-reg-db:
    build: ./wed-reg-db
    environment:
      - MYSQL_DATABASE="wedding"
      - MYSQL_ROOT_PASSWORD="root"
    ports:
      - "3307:3306"