# Specify a base image
FROM node:latest

ENV MYSQL_HOST="wed-reg-db" \
  MYSQL_DATABASE="wedding" \
  MYSQL_USER="webuser" \
  MYSQL_PASSWORD="0219MrsDenny!" \
  MYSQL_ROOT_PASSWORD="1234556789" \
  MYSQL_PORT="3307" \
  HTTPS=true \
  JWT_SECRET="totallyunguessablesecrethereforjsonwt"

WORKDIR /usr/app/src
COPY ./ ./
RUN npm install --no-audit

# Set up a default command
CMD [ "npm", "run", "start" ]