# Specify a base image
FROM node:latest

ENV MYSQL_HOST="db" \
  MYSQL_DATABASE="wedding" \
  MYSQL_USER="webuser" \
  MYSQL_PASSWORD="0219MrsDenny!" \
  MYSQL_ROOT_PASSWORD="1234556789" \
  MYSQL_PORT="3307" \
  HTTPS=true \
  JWT_SECRET="totallyunguessablesecrethereforjsonwt"

WORKDIR /app

COPY ./package.json /app/package.json
COPY ./package-lock.json /app/package-lock.json

RUN npm install
COPY . .

# Set up a default command
CMD [ "npm", "run", "start" ]