# Specify a base image
FROM node:latest

WORKDIR /app

COPY ./startup.sh /app/startup/startup.sh

RUN chmod +x /app/startup/startup.sh
RUN /app/startup/startup.sh

COPY ./package.json /app/package.json
COPY ./package-lock.json /app/package-lock.json

RUN npm install
COPY . .

# Set up a default command
CMD [ "npm", "run", "start" ]